[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
SUPABASE_URL = "${{SUPABASE_URL}}"
SUPABASE_SERVICE_ROLE_KEY = "${{SUPABASE_SERVICE_ROLE_KEY}}"
ANTHROPIC_API_KEY = "${{ANTHROPIC_API_KEY}}"
JWT_SECRET = "${{JWT_SECRET}}"
NODE_ENV = "production"

[environments.staging]
SUPABASE_URL = "${{SUPABASE_URL_STAGING}}"
SUPABASE_SERVICE_ROLE_KEY = "${{SUPABASE_SERVICE_ROLE_KEY_STAGING}}"
ANTHROPIC_API_KEY = "${{ANTHROPIC_API_KEY}}"
JWT_SECRET = "${{JWT_SECRET}}"
NODE_ENV = "staging"
